### ISSUE TITLE
Container not start

### ISSUE THREAD

**Issue by golya87** [XMRto/monero#3]
I was trying to switch from one of your older (monero:patched) container to a newer one, but it dies right after the start without any logs or erros.

With the "patched" version it is working, but the others aren't, even if I just use the basic `docker run --rm -it xmrto/monero:v0.14.0.1` command

`docker run --rm --name=monerod -p 18080:18080 -p 18081:18081 -v /blck/monerod:/monero -e USER_ID=1016 -e RPC_BIND_IP=0.0.0.0 -e RPC_BIND_PORT=18081 -e P2P_BIND_IP=0.0.0.0 -e P2P_BIND_PORT=18080 -e LOG_LEVEL=1 xmrto/monero:patched --data-dir /monero --non-interactive`

What did I miss?

**Comment by normoes** [comment]
Hey there,

First of all, thanks for reaching out to us :)
I would recommend to  use the tag `xmrto/monero:most_recent_tag`.

The actual question is, what kind of system are you using. Could you please report the architecture you are working with - Something like `uname -a`.
I had some issue (and a similar behaviour) when compiling dynamically and running on another architecture.

If your error persists, please report back and I'll switch to a static build instead.

Meanwhile you could try to do the following:
Run:
```
docker run --rm -it --name=monerod -p 18080:18080 -p 18081:18081 -v /blck/monerod:/monero -e USER_ID=1016 -e RPC_BIND_IP=0.0.0.0 -e RPC_BIND_PORT=18081 -e P2P_BIND_IP=0.0.0.0 -e P2P_BIND_PORT=18080 -e LOG_LEVEL=1 --entrypoint="" xmrto/monero:most_recent_tag bash
```
This disables the entrypoint script. You will end up in the container. 

Now Try to do the followwing:
```
# just to see the output
$ monerod --version
# try to run monerod, e.g.:
$ monerod --stagenet
# and try to execute the entrypoint script
$ /entrypoint.sh
```

It would be interesting to see the output of these commands executed directly from within the container.

**Comment by golya87** [comment]
Hello Norman,

These are the outputs:
```
root@JARVIS:~# uname -a
Linux JARVIS 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 GNU/Linux

root@ac8aec029598:/monero# monerod --version
Illegal instruction (core dumped)
root@ac8aec029598:/monero# monerod --stagenet
Illegal instruction (core dumped)
root@ac8aec029598:/monero# /entrypoint.sh
monerod --log-level 1 --confirm-external-bind --rpc-bind-ip 0.0.0.0 --rpc-bind-port 18081 --p2p-bind-ip 0.0.0.0 --p2p-bind-port 18080 --check-updates disabled
Illegal instruction (core dumped)
```

Thanks for your help!

**Comment by normoes** [comment]
I will create a static build tomorrow - That's the problem.

I am going to report back to you once I'm done.

**Comment by normoes** [comment]
Short information:

Waiting for the ci/cd to finish - Could take some time.

**Comment by golya87** [comment]
Yesterday evening I've pulled the new "most_recent_tag" version and it's worked, I'm in sync now.

Thank you for your help!
