### ISSUE TITLE
Automatically expose ports to the host machine

### ISSUE THREAD

**Issue by thomaseizinger** [XMRto/monero#9]
The `docker` CLI allows users to automatically assign a free host port to all exposed ports of an image with the `-p` argument.

However, this only works if the image uses the [`EXPOSE`](https://docs.docker.com/engine/reference/builder/#expose) instruction.

It would be useful if the docker image would have an `EXPOSE` instruction for the ports `28080` and `28081` so that they are automatically bound to the host machine if the image is started with `-p`.

**Comment by normoes** [comment]
Hi,

Thanks for the hint.
This should also solve the other issue: https://github.com/XMRto/monero/issues/2

I will `EXPOSE` all the common network ports then:
* `18080`
* `18081`
* `28080`
* `28081`
* `38080`
* `38081`

With this approach your suggestion works for all Monero network types and the Monero wallet rpc as well.

What do you think?

**Comment by normoes** [comment]
I was hesitant to implement this, because the ports themselves are configurable in the doker image.

But it seems, this will help people using the image. +1

**Comment by thomaseizinger** [comment]
> I was hesitant to implement this, because the ports themselves are configurable in the doker image.

That is true! However, in this case I think a user would accept that they have to manually specify which ports are exposed? Having the default ports exposed by default definitely helps! Thank you!

**Comment by normoes** [comment]
@thomaseizinger 

You can try this with, the builds are finished:
* `docker pull xmrto/monero:latest`
* `docker pull xmrto/monero:v0.17.1.5`

**Comment by normoes** [comment]
Closing as it is implemented.
